
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[░▒▓](red)\
$os\
$username\
[ ](bg:blue fg:red)\
$directory\
[ ](bg:yellow fg:blue)\
$git_branch\
$git_commit\
$git_status\
[ ](fg:yellow bg:green)\
$python\
$rust\
[ ](fg:green bg:background)\
$line_break\
$character\
"""

palette = 'tomorrow_night'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' 

[os]
disabled = false
style = "bg:red fg:black"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Alpine = ""
Arch = "󰣇"
Debian = "󰣚"
EndeavourOS = "󰣇"

[username]
show_always = true
style_user = "bg:red fg:black"
style_root = "bg:red fg:red"
format = '[ $user ]($style)'

[directory]
style = "bg:blue fg:black"
format = "[$path]($style)"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[$symbol $branch ](fg:black bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind)](fg:black bg:yellow)]($style)'

[git_commit]
tag_symbol = ' 󰓹 '
style = "bg:yellow"
format =  '[[$tag](fg:black bg:yellow)]($style)'
tag_disabled = false
only_detached = false

[python]
symbol = ' '
style = "bg:green fg:black"
pyenv_version_name = true
pyenv_prefix = 'pyenv: '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.tomorrow_night]
# Official Tomorrow Night colors
red = "#cc6666"
orange = "#de935f"
yellow = "#f0c674"
green = "#b5bd68"
aqua = "#8abeb7"
blue = "#81a2be"
purple = "#b294bb"
foreground = "#c5c8c6"
background = "#1d1f21"
current_line = "#282a2e"
selection = "#373b41"
comment = "#969896"
window = "#4d5057"
